/* Influente per le query:
1.4 - Operazione di uguaglianza nel WHERE su OPERA_TITOLO */
CREATE INDEX IDX_TITOLO ON OPERA_AUDIOVISIVA USING HASH (TITOLO);

/* Influente per le query:
1.9, 2.1 - Operazione di uguaglianza nel WHERE su COD_OPERA */
CREATE INDEX IDX_COD_OP_REC ON RECENSIONE USING HASH (COD_OPERA);

/* Influente per le query:
1.13, 1.14, 2.6 - Operazione di uguaglianza nel WHERE su COMMENTO.COD_SPETTATORE_SCRIVE */
CREATE INDEX IDX_SPET_SCRIVE ON COMMENTO USING HASH (COD_SPETTATORE_SCRIVE);

/* Influente per le query:
2.3 - Operazione di ORDER_BY su RECENSIONE.TIMESTAMP_CONT
2.4 - Operazione di ORDER_BY su RECENSIONE.TIMESTAMP_CONT */
CREATE INDEX IDX_TIMESTAMP_REC ON RECENSIONE USING BTREE (TIMESTAMP_CONT);
CLUSTER RECENSIONE USING IDX_TIMESTAMP_REC;

CREATE INDEX IDX_TIMESTAMP_COM ON COMMENTO USING BTREE (TIMESTAMP_CONT);
CLUSTER COMMENTO USING IDX_TIMESTAMP_COM;