/* Privilegi assegnati a UTENTE_SPECT */
GRANT SELECT ON TABLE OPERA_PRODUZIONE_VIEW TO UTENTE_SPECT;
GRANT SELECT ON TABLE INFO_OPERA_VIEW TO UTENTE_SPECT;

GRANT SELECT ON TABLE OPERA_AUDIOVISIVA TO UTENTE_SPECT;
GRANT SELECT ON TABLE NOMINATA_IN_OE TO UTENTE_SPECT;
GRANT SELECT ON TABLE NOMINATA_IN_VENEZIA TO UTENTE_SPECT;
GRANT SELECT ON TABLE RECENSIONE TO UTENTE_SPECT;
GRANT SELECT ON TABLE COMMENTO TO UTENTE_SPECT;

GRANT INSERT ON TABLE ISCRIZIONE TO UTENTE_SPECT;
GRANT INSERT ON TABLE VOTA_SPETTATORE TO UTENTE_SPECT;
GRANT INSERT ON TABLE RECENSIONE TO UTENTE_SPECT;
GRANT INSERT ON TABLE COMMENTO TO UTENTE_SPECT;
GRANT INSERT ON TABLE SEGUE TO UTENTE_SPECT;

/* Privilegi assegnati a UTENTE_GIURATO */
GRANT SELECT ON TABLE OPERA_PRODUZIONE_VIEW TO UTENTE_GIURATO;
GRANT SELECT ON TABLE INFO_OPERA_VIEW TO UTENTE_GIURATO;

GRANT SELECT ON TABLE OPERA_AUDIOVISIVA TO UTENTE_GIURATO;
GRANT SELECT ON TABLE NOMINATA_IN_OE TO UTENTE_GIURATO;
GRANT SELECT ON TABLE NOMINATA_IN_VENEZIA TO UTENTE_GIURATO;

GRANT INSERT ON TABLE VOTA_ATTORE TO UTENTE_GIURATO;
GRANT INSERT ON TABLE VOTA_REGISTA TO UTENTE_GIURATO;
GRANT INSERT ON TABLE VOTA_GIORNALISTA TO UTENTE_GIURATO;