/* View che unisce le tabelle OPERA_AUDIOVISIVA e PRODUZIONE */
CREATE VIEW OPERA_PRODUZIONE_VIEW AS
(SELECT 
    OPERA_AUDIOVISIVA.COD_OPERA,
    EPISODIO.COD_PROD,
    OPERA_AUDIOVISIVA.TITOLO AS Opera_Titolo,
    EPISODIO.TITOLO AS Titolo_Episodio,
    EPISODIO.NUM_STAGIONE,
    EPISODIO.NUM_EPISODIO,
    PRODUZIONE.MINUTAGGIO,
    PRODUZIONE.COD_REGISTA
FROM 
    EPISODIO
JOIN 
    STAGIONE ON EPISODIO.COD_OPERA = STAGIONE.COD_OPERA AND STAGIONE.NUM = EPISODIO.NUM_STAGIONE
JOIN 
    OPERA_AUDIOVISIVA ON EPISODIO.COD_OPERA = OPERA_AUDIOVISIVA.COD_OPERA
JOIN 
    PRODUZIONE ON EPISODIO.COD_PROD = PRODUZIONE.COD_PROD

UNION

SELECT 
    OPERA_AUDIOVISIVA.COD_OPERA,
    FILM.COD_PROD,
    OPERA_AUDIOVISIVA.TITOLO AS Opera_Titolo,
	NULL AS Titolo_Episodio,
    NULL AS NUM_STAGIONE,
    NULL AS NUM_EPISODIO,
    PRODUZIONE.MINUTAGGIO,
	PRODUZIONE.COD_REGISTA
FROM 
    FILM
JOIN 
    OPERA_AUDIOVISIVA ON FILM.COD_OPERA = OPERA_AUDIOVISIVA.COD_OPERA
JOIN 
    PRODUZIONE ON FILM.COD_PROD = PRODUZIONE.COD_PROD
);

/* View che racchiude tutte le informazioni sulle opere audiovisiva presenti */
CREATE VIEW INFO_OPERA_VIEW AS
(SELECT 
    OPERA_AUDIOVISIVA.COD_OPERA,
    EPISODIO.COD_PROD,
    OPERA_AUDIOVISIVA.TITOLO AS Opera_Titolo,
    EPISODIO.TITOLO AS Titolo_Episodio,
    EPISODIO.NUM_STAGIONE,
    EPISODIO.NUM_EPISODIO,
    PRODUZIONE.MINUTAGGIO,
 	PRODUZIONE.GENERE,
    REGISTA.NOME AS NOME_REGISTA,
 	REGISTA.COGNOME AS COGNOME_REGISTA,
	ATTORE.NOME AS NOME_ATTORE,
 	ATTORE.COGNOME AS COGNOME_ATTORE
FROM 
    EPISODIO
JOIN 
    STAGIONE ON EPISODIO.COD_OPERA = STAGIONE.COD_OPERA AND STAGIONE.NUM = EPISODIO.NUM_STAGIONE
JOIN 
    OPERA_AUDIOVISIVA ON EPISODIO.COD_OPERA = OPERA_AUDIOVISIVA.COD_OPERA
JOIN 
    PRODUZIONE ON EPISODIO.COD_PROD = PRODUZIONE.COD_PROD
JOIN
 	REGISTA ON PRODUZIONE.COD_REGISTA = REGISTA.COD_REGISTA
JOIN 
 	CAST_PROD ON CAST_PROD.COD_PROD = EPISODIO.COD_PROD
JOIN
 	ATTORE ON CAST_PROD.COD_ATTORE = ATTORE.COD_ATTORE

 
UNION

SELECT 
    OPERA_AUDIOVISIVA.COD_OPERA,
    FILM.COD_PROD,
    OPERA_AUDIOVISIVA.TITOLO AS Opera_Titolo,
	NULL AS Titolo_Episodio,
    NULL AS NUM_STAGIONE,
    NULL AS NUM_EPISODIO,
    PRODUZIONE.MINUTAGGIO,
 	PRODUZIONE.GENERE,
    REGISTA.NOME AS NOME_REGISTA,
 	REGISTA.COGNOME AS COGNOME_REGISTA,
	ATTORE.NOME AS NOME_ATTORE,
 	ATTORE.COGNOME AS COGNOME_ATTORE
FROM 
    FILM
JOIN 
    OPERA_AUDIOVISIVA ON FILM.COD_OPERA = OPERA_AUDIOVISIVA.COD_OPERA
JOIN 
    PRODUZIONE ON FILM.COD_PROD = PRODUZIONE.COD_PROD
JOIN
 	REGISTA ON PRODUZIONE.COD_REGISTA = REGISTA.COD_REGISTA
JOIN 
 	CAST_PROD ON CAST_PROD.COD_PROD = FILM.COD_PROD
JOIN
 	ATTORE ON CAST_PROD.COD_ATTORE = ATTORE.COD_ATTORE
);

/* View utilizzata per ottenere i dati sulle votazioni dei giurati */
CREATE VIEW VOTI_GIURATO_VIEW AS (
	SELECT ANNATA_VENEZIA, COD_OPERA FROM
		(
			SELECT * FROM VOTA_ATTORE
				UNION
			SELECT * FROM VOTA_REGISTA
				UNION
			SELECT * FROM VOTA_GIORNALISTA
		)
);

/* Creata view di appoggio per i trigger */
CREATE VIEW ISCRIZIONE_CON_OPERA_VIEW AS (
	SELECT ISCRIZIONE.COD_PROD, COD_OPERA, DATA_PROIEZIONE, ORA, COD_SPETTATORE FROM ISCRIZIONE 
	JOIN FILM ON ISCRIZIONE.COD_PROD = FILM.COD_PROD

	UNION

	SELECT ISCRIZIONE.COD_PROD, COD_OPERA, DATA_PROIEZIONE, ORA, COD_SPETTATORE FROM ISCRIZIONE
	JOIN EPISODIO ON ISCRIZIONE.COD_PROD = EPISODIO.COD_PROD
);